steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  entrypoint: 'bash'
  args: [
    'build', 
    '--provenance=false',
    '-t', 'asia-south1-docker.pkg.dev/hgu-variationdb/cloud-run-source-deploy/slgvd_backend/slgvd-backend:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: ['push', 'asia-south1-docker.pkg.dev/hgu-variationdb/cloud-run-source-deploy/slgvd_backend/slgvd-backend:$SHORT_SHA']

# A small 5-second wait to ensure Artifact Registry is fully synced
- name: 'ubuntu'
  id: 'Wait'
  args: ['sleep', '5']
  
# Run Database Migrations
- name: 'gcr.io/google-appengine/exec-wrapper'
  id: 'Migrate'
  args:
    - '-i', 'asia-south1-docker.pkg.dev/hgu-variationdb/cloud-run-source-deploy/slgvd_backend/slgvd-backend:$SHORT_SHA'
    - '-s', 'hgu-variationdb:us-central1:variation-db'
    - '--', 'python', 'manage.py', 'migrate', '--noinput'
  env:
    - 'DATABASES_URL=mysql://test-user-1:123456@127.0.0.1:3306/GV_2'
    
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
entrypoint: gcloud
timeout: 900s
args: 
  - 'run'
  - 'deploy'
  - 'slgvd-backend'
  - '--image'
  - 'asia-south1-docker.pkg.dev/hgu-variationdb/cloud-run-source-deploy/slgvd_backend/slgvd-backend:$SHORT_SHA'
  - '--region'
  - 'asia-south1'
  - '--platform'
  - 'managed'
  - '--network'
  - 'default'
  - '--subnet'
  - 'default'
  - '--allow-unauthenticated'
  - '--port=8080'
  - '--add-cloudsql-instances=hgu-variationdb:us-central1:variation-db'


- name: gcr.io/google.com/cloudsdktool/cloud-sdk
entrypoint: gcloud
args:
  - 'run'
  - 'jobs'
  - 'deploy'
  - 'vcf-parser'
  - '--image'
  - 'asia-south1-docker.pkg.dev/hgu-variationdb/cloud-run-source-deploy/slgvd_backend/slgvd-backend:$SHORT_SHA'
  - '--region'
  - 'asia-south1'
  - '--platform'
  - 'managed'
  - '--network'
  - 'default'
  - '--subnet'
  - 'default'
  - '--no-allow-unauthenticated'
  - '--add-cloudsql-instances=hgu-variationdb:us-central1:variation-db'

options:
  requestedVerifyOption: VERIFY
  # This is the key: it tells Cloud Build NOT to generate provenance metadata
  substitutionOption: ALLOW_LOOSE
  pool:
    name: ''
  # Disable the automatic generation of provenance
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

# suppress the metadata
images:
  - 'asia-south1-docker.pkg.dev/hgu-variationdb/cloud-run-source-deploy/slgvd_backend/slgvd-backend:$SHORT_SHA'

# global setting:
artifacts:
  images:
    - 'asia-south1-docker.pkg.dev/hgu-variationdb/cloud-run-source-deploy/slgvd_backend/slgvd-backend:$SHORT_SHA'










