steps:
- name: 'gcr.io/cloud-builders/docker'
args: ['build', '-t', 'asia-south1-docker.pkg.dev/hgu-variationdb/slgvd-docker-repo/slgvd_backend:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
args: ['push', 'asia-south1-docker.pkg.dev/hgu-variationdb/slgvd-docker-repo/slgvd_backend:$SHORT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
entrypoint: gcloud
args: [
  'run', 'deploy', 'slgvd-backend',
  '--image', 'asia-south1-docker.pkg.dev/hgu-variationdb/slgvd-docker-repo/slgvd_backend:$SHORT_SHA',
  '--region', 'asia-south1',
  '--platform', 'managed',
  '--network', 'default',
  '--subnet', 'default',
  '--allow-unauthenticated',
  '--port=8080',
  '--timeout', '900s',
  '--add-cloudsql-instances=hgu-variationdb:us-central1:variation-db',
  '--set-env-vars',
  'DEBUG=False,REDIS_HOST=10.246.200.203,SECRET_KEY=django-insecure-!!wso6cw*0%f_p%lo-&-4q_&^!j2e4^mj(e8%5=t79it!z2yj4,USE_CLOUD_SQL_AUTH_PROXY=true,DATABASES_URL=mysql://test-user-1:123456@//cloudsql/localhost:3306/GV_2'
]

images: ['asia-south1-docker.pkg.dev/hgu-variationdb/slgvd-docker-repo/slgvd_backend:$SHORT_SHA']