steps:
- name: 'gcr.io/cloud-builders/docker'
args: ['build', '-t', 'asia-south1-docker.pkg.dev/hgu-variationdb/cloud-run-source-deploy/slgvd_backend/slgvd-backend:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
args: ['push', 'asia-south1-docker.pkg.dev/hgu-variationdb/cloud-run-source-deploy/slgvd_backend/slgvd-backend:$SHORT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
entrypoint: gcloud
timeout: 900s
args: 
  - 'run'
  - 'deploy'
  - 'slgvd-backend'
  - '--image'
  - 'asia-south1-docker.pkg.dev/hgu-variationdb/cloud-run-source-deploy/slgvd_backend/slgvd-backend:$SHORT_SHA'
  - '--region'
  - 'asia-south1'
  - '--platform'
  - 'managed'
  - '--network'
  - 'default'
  - '--subnet'
  - 'default'
  - '--allow-unauthenticated'
  - '--port=8080'
  - '--add-cloudsql-instances=hgu-variationdb:us-central1:variation-db'


- name: gcr.io/google.com/cloudsdktool/cloud-sdk
entrypoint: gcloud
args:
  - 'run'
  - 'jobs'
  - 'deploy'
  - 'vcf-parser'
  - '--image'
  - 'asia-south1-docker.pkg.dev/hgu-variationdb/cloud-run-source-deploy/slgvd_backend/slgvd-backend:$SHORT_SHA'
  - '--region'
  - 'asia-south1'
  - '--platform'
  - 'managed'
  - '--network'
  - 'default'
  - '--subnet'
  - 'default'
  - '--no-allow-unauthenticated'
  - '--add-cloudsql-instances=hgu-variationdb:us-central1:variation-db'

images: 

- 'asia-south1-docker.pkg.dev/hgu-variationdb/cloud-run-source-deploy/slgvd_backend/slgvd-backend:$SHORT_SHA'








